# Generated by Django 2.2.3 on 2019-07-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gonderi',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
