# Generated by Django 2.2.3 on 2019-07-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190720_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(max_length=280)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('gonderi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='yorumlar', to='blog.Gonderi')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
