# Generated by Django 2.2.3 on 2019-07-20 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderi',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gonderi',
            name='baslik',
            field=models.CharField(max_length=32, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='gonderi',
            name='icerik',
            field=models.TextField(verbose_name='İçerik'),
        ),
    ]
